services:
  dev:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}

    image: gensc_bench:latest
    container_name: gensc_bench_container

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    working_dir: /workspace

    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]